services:
  mt5linux:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mt5-headless
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /tmp/mt5:/app
